name: Atualizar versão no servidor

on:
  push:
    branches:
      - main

jobs:
  update-server-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Pegar o commit hash
      id: commit
      run: echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Conectar via SSH e escrever commit
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "${{ env.COMMIT_ID }}" > /home/ec2-user/commit_id.txt
